import {MAP_ATLASES,MAP_ASSETS,MAP_LAYERS,assetById,cloneMapDocument,createMapImages,drawMapGround,drawMapObjects,drawMapGeometry,loadMapDocument,mapId,placeMapObject,pointInObject,pointInRect,removeMapEntity,resetMapDocument,resolveMapCollisions,sanitizeMapDocument,saveMapDocument} from './map-document.js?v=20260813-1';

const canvas=document.querySelector('#map-canvas'),ctx=canvas.getContext('2d',{alpha:false}),stage=document.querySelector('#maker-stage');
const assetGrid=document.querySelector('#asset-grid'),layerList=document.querySelector('#layer-list'),fileInput=document.querySelector('#map-file');
const images=createMapImages();let documentModel=loadMapDocument(),activeTool='select',activePalette='terrain',activeLayer='ground',selectedAssetId='terrain-0',selectedId=null;
for(const image of Object.values(images)){image.addEventListener('load',()=>render(),{once:true});image.addEventListener('error',()=>render(),{once:true});}
let gridVisible=true,snapEnabled=true,playtesting=false,spaceHeld=false,pointer=null,gesture=null,saveTimer=null;
let camera={x:documentModel.width/2,y:documentModel.height/2,zoom:.3};
const history=[],future=[],keys=new Set(),testPlayer={x:2400,y:1480,vx:0,vy:0,radius:28,facing:0};
const toolHelp={select:['SELECT','Click an object or shape · drag to move · Delete removes'],brush:['FLOOR BRUSH','Choose a floor tile · click and drag to paint'],object:['PLACE OBJECT','Choose a building or prop · click to place · linked collision is created'],erase:['ERASER','Click or drag to remove tiles, objects, or shapes'],collision:['COLLISION RECTANGLE','Drag a rectangle around solid space'],trigger:['TRIGGER RECTANGLE','Drag an interaction or event area'],spawn:['PLAYER SPAWN','Click where the player should enter the village'],pan:['PAN CAMERA','Click and drag the map · mouse wheel zooms']};

function resize(){const rect=stage.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));canvas.dataset.dpr=dpr;render();}
function screenToWorld(clientX,clientY){const rect=canvas.getBoundingClientRect();return {x:camera.x+(clientX-rect.left-rect.width/2)/camera.zoom,y:camera.y+(clientY-rect.top-rect.height/2)/camera.zoom};}
function worldView(){const rect=canvas.getBoundingClientRect();return {left:camera.x-rect.width/(2*camera.zoom),right:camera.x+rect.width/(2*camera.zoom),top:camera.y-rect.height/(2*camera.zoom),bottom:camera.y+rect.height/(2*camera.zoom)};}
function snap(value,size=documentModel.tileSize){return snapEnabled?Math.round(value/size)*size:value;}
function clampCamera(){const rect=canvas.getBoundingClientRect(),pad=240/camera.zoom;camera.x=Math.max(-pad,Math.min(documentModel.width+pad,camera.x));camera.y=Math.max(-pad,Math.min(documentModel.height+pad,camera.y));}
function worldTransform(){const dpr=Number(canvas.dataset.dpr)||1,rect=canvas.getBoundingClientRect();ctx.setTransform(dpr*camera.zoom,0,0,dpr*camera.zoom,dpr*(rect.width/2-camera.x*camera.zoom),dpr*(rect.height/2-camera.y*camera.zoom));}

function render(){
  const dpr=Number(canvas.dataset.dpr)||1,rect=canvas.getBoundingClientRect();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#050810';ctx.fillRect(0,0,rect.width,rect.height);worldTransform();
  const view=worldView();drawMapGround(ctx,documentModel,images,{view,grid:gridVisible&&!playtesting});drawMapObjects(ctx,documentModel,images,{view,includeForeground:false,selectedId:playtesting?null:selectedId});
  if(!playtesting)drawMapGeometry(ctx,documentModel,{collisions:true,triggers:true,spawns:true,selectedId});
  if(gesture?.type==='rect'){const x=Math.min(gesture.start.x,gesture.current.x),y=Math.min(gesture.start.y,gesture.current.y),width=Math.abs(gesture.current.x-gesture.start.x),height=Math.abs(gesture.current.y-gesture.start.y);ctx.save();ctx.fillStyle=activeTool==='collision'?'rgba(255,67,101,.28)':'rgba(205,62,255,.24)';ctx.strokeStyle=activeTool==='collision'?'#ff526f':'#d852ff';ctx.lineWidth=5/camera.zoom;ctx.setLineDash([14/camera.zoom,8/camera.zoom]);ctx.fillRect(x,y,width,height);ctx.strokeRect(x,y,width,height);ctx.restore();}
  if(playtesting)drawTestPlayer();drawMapObjects(ctx,documentModel,images,{view,includeForeground:true});
  ctx.setTransform(dpr,0,0,dpr,0,0);document.querySelector('#zoom-level').textContent=`ZOOM ${Math.round(camera.zoom*100)}%`;
}

function drawTestPlayer(){ctx.save();ctx.translate(testPlayer.x,testPlayer.y);ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(0,9,25,9,0,0,Math.PI*2);ctx.fill();ctx.rotate(testPlayer.facing);ctx.fillStyle='#ec7d2d';ctx.strokeStyle='#fff4dd';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,-18,27,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(17,-18);ctx.lineTo(48,-8);ctx.lineTo(17,-2);ctx.closePath();ctx.fill();ctx.restore();}

function snapshot(){history.push(cloneMapDocument(documentModel));if(history.length>100)history.shift();future.length=0;updateHistoryButtons();}
function undo(){if(!history.length)return;future.push(cloneMapDocument(documentModel));documentModel=history.pop();selectedId=null;afterMutation(false);}
function redo(){if(!future.length)return;history.push(cloneMapDocument(documentModel));documentModel=future.pop();selectedId=null;afterMutation(false);}
function updateHistoryButtons(){document.querySelector('#undo').disabled=!history.length;document.querySelector('#redo').disabled=!future.length;}
function afterMutation(queueSave=true){refreshLayers();refreshInspector();refreshMapStats();render();if(queueSave)scheduleSave();}
function scheduleSave(){const state=document.querySelector('#save-state');state.textContent='SAVING…';state.classList.add('saving');clearTimeout(saveTimer);saveTimer=setTimeout(()=>{documentModel=saveMapDocument(documentModel);state.textContent='SAVED LOCALLY';state.classList.remove('saving');},180);}

function setTool(tool){if(playtesting)return;activeTool=tool;document.querySelectorAll('[data-tool]').forEach((button)=>button.classList.toggle('active',button.dataset.tool===tool));const help=toolHelp[tool];document.querySelector('#stage-help').innerHTML=`<b>${help[0]}</b><span>${help[1]}</span>`;canvas.style.cursor=tool==='pan'?'grab':tool==='select'?'default':'crosshair';if(tool==='brush'){activePalette='terrain';activeLayer=activeLayer==='groundDetail'?'groundDetail':'ground';refreshPaletteTabs();}else if(tool==='object'&&activePalette==='terrain'){activePalette='architecture';activeLayer='structures';refreshPaletteTabs();}refreshAssets();refreshLayers();}
function selectLayer(id){const layer=documentModel.layers.find((item)=>item.id===id);if(!layer)return;activeLayer=id;if(layer.kind==='tile'){activePalette='terrain';setTool('brush');}else if(layer.kind==='object'){if(activePalette==='terrain')activePalette=id==='props'?'props':'architecture';setTool('object');}else if(id==='collision')setTool('collision');else if(id==='triggers')setTool('trigger');else if(id==='spawns')setTool('spawn');refreshLayers();refreshAssets();}

function refreshPaletteTabs(){document.querySelectorAll('[data-palette]').forEach((button)=>button.classList.toggle('active',button.dataset.palette===activePalette));}
function previewStyle(asset){const atlas=MAP_ATLASES[asset.atlas],col=asset.frame%atlas.columns,row=Math.floor(asset.frame/atlas.columns),x=atlas.columns===1?0:col/(atlas.columns-1)*100,y=atlas.rows===1?0:row/(atlas.rows-1)*100;return `background-image:url('${atlas.src}');background-size:${atlas.columns*100}% ${atlas.rows*100}%;background-position:${x}% ${y}%`}
function refreshAssets(){
  refreshPaletteTabs();const query=document.querySelector('#asset-search').value.trim().toLowerCase(),assets=MAP_ASSETS[activePalette].filter((asset)=>!query||asset.name.toLowerCase().includes(query));document.querySelector('#palette-count').textContent=`${assets.length} ASSETS`;
  assetGrid.innerHTML=assets.map((asset)=>`<button class="asset-card ${asset.id===selectedAssetId?'selected':''}" data-asset="${asset.id}" title="${asset.name}"><span class="asset-preview" style="${previewStyle(asset)}"></span><em>${asset.category==='terrain'?'TILE':asset.category==='architecture'?'BUILDING':'PROP'}</em><b>${asset.name}</b></button>`).join('');
  for(const button of assetGrid.querySelectorAll('[data-asset]'))button.addEventListener('click',()=>{selectedAssetId=button.dataset.asset;const asset=assetById(selectedAssetId);if(asset.category==='terrain'){activeLayer=activeLayer==='groundDetail'?'groundDetail':'ground';setTool('brush');}else{activeLayer=asset.category==='architecture'?'structures':'props';setTool('object');}refreshAssets();});
}

function refreshLayers(){layerList.innerHTML=documentModel.layers.slice().reverse().map((layer)=>`<div class="layer-row ${layer.id===activeLayer?'active':''}" data-layer="${layer.id}"><button data-visible title="Toggle visibility">${layer.visible===false?'○':'◉'}</button><div><b>${layer.name}</b><small>${layer.kind.toUpperCase()}</small></div><button data-lock title="Toggle lock">${layer.locked?'▣':'▢'}</button></div>`).join('');for(const row of layerList.querySelectorAll('[data-layer]')){row.addEventListener('click',(event)=>{if(event.target.closest('[data-visible]')||event.target.closest('[data-lock]'))return;selectLayer(row.dataset.layer);});row.querySelector('[data-visible]').addEventListener('click',()=>{const layer=documentModel.layers.find((item)=>item.id===row.dataset.layer);snapshot();layer.visible=!layer.visible;afterMutation();});row.querySelector('[data-lock]').addEventListener('click',()=>{const layer=documentModel.layers.find((item)=>item.id===row.dataset.layer);snapshot();layer.locked=!layer.locked;afterMutation();});}document.querySelector('#active-layer-label').textContent=`LAYER ${activeLayer.toUpperCase()}`;}
function currentEntity(){return documentModel.objects.find((item)=>item.id===selectedId)||documentModel.collisions.find((item)=>item.id===selectedId)||documentModel.triggers.find((item)=>item.id===selectedId)||documentModel.spawns.find((item)=>item.id===selectedId)||null;}
function entityKind(entity){if(!entity)return '';if(documentModel.objects.includes(entity))return 'OBJECT';if(documentModel.collisions.includes(entity))return 'COLLISION';if(documentModel.triggers.includes(entity))return 'TRIGGER';return 'SPAWN';}
function refreshInspector(){
  const entity=currentEntity(),form=document.querySelector('#entity-inspector'),empty=document.querySelector('#empty-inspector');empty.hidden=Boolean(entity);form.hidden=!entity;document.querySelector('#selection-kind').textContent=entity?entityKind(entity):'NOTHING SELECTED';if(!entity)return;
  document.querySelector('#entity-name').value=entity.name||'';document.querySelector('#entity-x').value=Math.round(entity.x);document.querySelector('#entity-y').value=Math.round(entity.y);document.querySelector('#entity-width').value=Math.round(entity.width||1);document.querySelector('#entity-height').value=Math.round(entity.height||1);document.querySelector('#entity-rotation').value=Math.round((entity.rotation||0)*180/Math.PI);document.querySelector('#entity-opacity').value=Math.round((entity.opacity??1)*100);
  const object=documentModel.objects.includes(entity);document.querySelector('#rotation-field').hidden=!object;document.querySelector('#opacity-field').hidden=!object;document.querySelector('#entity-width').closest('label').hidden=entityKind(entity)==='SPAWN';document.querySelector('#entity-height').closest('label').hidden=entityKind(entity)==='SPAWN';const layerSelect=document.querySelector('#entity-layer');layerSelect.innerHTML=documentModel.layers.filter((layer)=>object?layer.kind==='object':layer.id===entity.layer).map((layer)=>`<option value="${layer.id}" ${layer.id===entity.layer?'selected':''}>${layer.name}</option>`).join('');
}
function refreshMapStats(){document.querySelector('#map-size').textContent=`${documentModel.width} × ${documentModel.height}`;document.querySelector('#grid-size').textContent=`${documentModel.tileSize} PX`;document.querySelector('#object-count').textContent=documentModel.objects.length;document.querySelector('#collision-count').textContent=documentModel.collisions.length;document.querySelector('#map-name').value=documentModel.name;}

function hitTest(point){
  if(activeLayer==='collision'||activeTool==='collision')for(const entity of documentModel.collisions.slice().reverse())if(pointInRect(point,entity))return entity;
  if(activeLayer==='triggers'||activeTool==='trigger')for(const entity of documentModel.triggers.slice().reverse())if(pointInRect(point,entity))return entity;
  if(activeLayer==='spawns'||activeTool==='spawn')for(const entity of documentModel.spawns.slice().reverse())if(Math.hypot(point.x-entity.x,point.y-entity.y)<55/camera.zoom)return entity;
  for(const object of documentModel.objects.slice().sort((a,b)=>b.y-a.y))if(pointInObject(point,object))return object;
  for(const collection of [documentModel.collisions,documentModel.triggers])for(const entity of collection.slice().reverse())if(pointInRect(point,entity))return entity;
  return null;
}
function paintAt(point,erase=false){const col=Math.floor(point.x/documentModel.tileSize),row=Math.floor(point.y/documentModel.tileSize);if(col<0||row<0||col>=documentModel.columns||row>=documentModel.rows)return;const index=row*documentModel.columns+col,value=erase?(activeLayer==='ground' ? 8 : -1):assetById(selectedAssetId)?.frame??0;if(documentModel.tiles[activeLayer]?.[index]===value)return;documentModel.tiles[activeLayer][index]=value;gesture.changed=true;render();}
function eraseAt(point){const hit=hitTest(point);if(hit){removeMapEntity(documentModel,hit.id);selectedId=null;gesture.changed=true;afterMutation(false);return;}activeLayer=documentModel.layers.find((layer)=>layer.id===activeLayer)?.kind==='tile'?activeLayer:'groundDetail';paintAt(point,true);}

function onPointerDown(event){
  if(playtesting)return;canvas.setPointerCapture(event.pointerId);pointer={id:event.pointerId,startClient:{x:event.clientX,y:event.clientY},lastClient:{x:event.clientX,y:event.clientY}};const point=screenToWorld(event.clientX,event.clientY),panning=event.button===1||spaceHeld||activeTool==='pan';
  if(panning){gesture={type:'pan',camera:{...camera}};canvas.style.cursor='grabbing';return;}
  if(event.button!==0)return;
  if(activeTool==='brush'){snapshot();gesture={type:'paint',changed:false};paintAt(point,false);}
  else if(activeTool==='erase'){snapshot();gesture={type:'erase',changed:false};eraseAt(point);}
  else if(activeTool==='object'){const asset=assetById(selectedAssetId);if(!asset||asset.category==='terrain')return;snapshot();const placed=placeMapObject(documentModel,asset.id,snap(point.x,documentModel.tileSize/2),snap(point.y,documentModel.tileSize/2),{layer:activeLayer});selectedId=placed.id;gesture={type:'placed',changed:true};afterMutation(false);}
  else if(activeTool==='collision'||activeTool==='trigger'){snapshot();gesture={type:'rect',start:{x:snap(point.x),y:snap(point.y)},current:{x:snap(point.x),y:snap(point.y)},changed:false};}
  else if(activeTool==='spawn'){snapshot();let spawn=documentModel.spawns.find((item)=>item.type==='player');if(!spawn){spawn={id:'player-spawn',name:'Player Spawn',type:'player',layer:'spawns',x:point.x,y:point.y};documentModel.spawns.push(spawn);}spawn.x=snap(point.x,documentModel.tileSize/2);spawn.y=snap(point.y,documentModel.tileSize/2);selectedId=spawn.id;gesture={type:'spawn',changed:true};afterMutation(false);}
  else if(activeTool==='select'){const hit=hitTest(point);selectedId=hit?.id||null;refreshInspector();render();if(hit){snapshot();gesture={type:'move',entityId:hit.id,start:{x:hit.x,y:hit.y},point,changed:false};}}
}
function onPointerMove(event){
  const point=screenToWorld(event.clientX,event.clientY);document.querySelector('#cursor-position').textContent=`X ${Math.round(point.x)} · Y ${Math.round(point.y)}`;if(!pointer||event.pointerId!==pointer.id)return;
  if(gesture?.type==='pan'){camera.x=gesture.camera.x-(event.clientX-pointer.startClient.x)/camera.zoom;camera.y=gesture.camera.y-(event.clientY-pointer.startClient.y)/camera.zoom;clampCamera();render();return;}
  if(gesture?.type==='paint')paintAt(point,false);else if(gesture?.type==='erase')eraseAt(point);else if(gesture?.type==='rect'){gesture.current={x:snap(point.x),y:snap(point.y)};render();}
  else if(gesture?.type==='move'){const entity=currentEntity();if(!entity)return;const oldX=entity.x,oldY=entity.y;entity.x=snap(gesture.start.x+point.x-gesture.point.x,documentModel.tileSize/2);entity.y=snap(gesture.start.y+point.y-gesture.point.y,documentModel.tileSize/2);const dx=entity.x-oldX,dy=entity.y-oldY;for(const collision of documentModel.collisions.filter((item)=>item.sourceObjectId===entity.id)){collision.x+=dx;collision.y+=dy;}gesture.changed=true;refreshInspector();render();}
}
function onPointerUp(event){
  if(!pointer||event.pointerId!==pointer.id)return;if(gesture?.type==='rect'){const x=Math.min(gesture.start.x,gesture.current.x),y=Math.min(gesture.start.y,gesture.current.y),width=Math.abs(gesture.current.x-gesture.start.x),height=Math.abs(gesture.current.y-gesture.start.y);if(width>=20&&height>=20){const entity={id:mapId(activeTool),name:activeTool==='collision'?'Collision':'Trigger',x,y,width,height,layer:activeTool==='collision'?'collision':'triggers',enabled:true};(activeTool==='collision'?documentModel.collisions:documentModel.triggers).push(entity);selectedId=entity.id;gesture.changed=true;}}
  const changed=gesture?.changed,type=gesture?.type;if(type==='pan')canvas.style.cursor=activeTool==='pan'?'grab':'crosshair';pointer=null;gesture=null;if(changed)afterMutation();else if(history.length&&['rect','move','paint','erase'].includes(type)){history.pop();updateHistoryButtons();}render();
}

function deleteSelected(){if(!selectedId)return;snapshot();removeMapEntity(documentModel,selectedId);selectedId=null;afterMutation();}
function duplicateSelected(){const entity=currentEntity();if(!entity)return;snapshot();const copy={...cloneMapDocument(entity),id:mapId(entityKind(entity).toLowerCase()),x:entity.x+60,y:entity.y+60,name:`${entity.name||'Entity'} Copy`};if(documentModel.objects.includes(entity)){documentModel.objects.push(copy);const linked=documentModel.collisions.find((item)=>item.sourceObjectId===entity.id);if(linked)documentModel.collisions.push({...linked,id:mapId('collision'),sourceObjectId:copy.id,x:linked.x+60,y:linked.y+60});}else if(documentModel.collisions.includes(entity))documentModel.collisions.push(copy);else if(documentModel.triggers.includes(entity))documentModel.triggers.push(copy);else documentModel.spawns.push(copy);selectedId=copy.id;afterMutation();}
function bindInspector(){for(const id of ['entity-name','entity-x','entity-y','entity-width','entity-height','entity-rotation','entity-opacity','entity-layer'])document.querySelector(`#${id}`).addEventListener('change',()=>{const entity=currentEntity();if(!entity)return;snapshot();const previous={x:entity.x,y:entity.y};entity.name=document.querySelector('#entity-name').value;entity.x=Number(document.querySelector('#entity-x').value)||0;entity.y=Number(document.querySelector('#entity-y').value)||0;if('width'in entity)entity.width=Math.max(1,Number(document.querySelector('#entity-width').value)||1);if('height'in entity)entity.height=Math.max(1,Number(document.querySelector('#entity-height').value)||1);if('rotation'in entity)entity.rotation=(Number(document.querySelector('#entity-rotation').value)||0)*Math.PI/180;if('opacity'in entity)entity.opacity=Math.max(0,Math.min(1,(Number(document.querySelector('#entity-opacity').value)||0)/100));entity.layer=document.querySelector('#entity-layer').value||entity.layer;for(const collision of documentModel.collisions.filter((item)=>item.sourceObjectId===entity.id)){collision.x+=entity.x-previous.x;collision.y+=entity.y-previous.y;}afterMutation();});}

function exportMap(){const blob=new Blob([JSON.stringify(sanitizeMapDocument(documentModel),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${documentModel.id||'brawlpaws-map'}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
async function importMap(file){try{const incoming=sanitizeMapDocument(JSON.parse(await file.text()));snapshot();documentModel=incoming;selectedId=null;camera={x:incoming.width/2,y:incoming.height/2,zoom:Math.min(stage.clientWidth/incoming.width,stage.clientHeight/incoming.height)*.85};afterMutation();}catch(error){alert(`That map could not be imported. ${error.message}`);}}
function resetStarter(){if(!confirm('Replace the current map with the starter component village? You can undo this afterward.'))return;snapshot();documentModel=resetMapDocument();selectedId=null;camera={x:documentModel.width/2,y:documentModel.height/2,zoom:.3};afterMutation();}
function newBlankMap(){if(!confirm('Create a blank map? Your current map remains available through Undo until this page closes.'))return;snapshot();const blank=resetMapDocument();blank.name='Untitled Village';blank.tiles.ground.fill(8);blank.tiles.groundDetail.fill(-1);blank.objects=[];blank.collisions=blank.collisions.filter((item)=>item.boundary);blank.triggers=[];documentModel=blank;selectedId=null;afterMutation();}

function togglePlaytest(){playtesting=!playtesting;document.querySelector('#playtest-banner').hidden=!playtesting;document.querySelector('#stage-help').hidden=playtesting;document.querySelector('#playtest').classList.toggle('active',playtesting);if(playtesting){const spawn=documentModel.spawns.find((item)=>item.type==='player')||{x:documentModel.width/2,y:documentModel.height/2};Object.assign(testPlayer,{x:spawn.x,y:spawn.y,vx:0,vy:0});canvas.style.cursor='none';}else canvas.style.cursor=activeTool==='select'?'default':'crosshair';render();}
let lastTime=performance.now();function frame(time){const dt=Math.min(.04,(time-lastTime)/1000);lastTime=time;if(playtesting){let x=(keys.has('d')?1:0)-(keys.has('a')?1:0),y=(keys.has('s')?1:0)-(keys.has('w')?1:0),length=Math.hypot(x,y)||1;x/=length;y/=length;const speed=keys.has('shift')?620:360,previous={x:testPlayer.x,y:testPlayer.y};testPlayer.vx=x*speed;testPlayer.vy=y*speed;testPlayer.x+=testPlayer.vx*dt;testPlayer.y+=testPlayer.vy*dt;if(x||y)testPlayer.facing=Math.atan2(y,x);resolveMapCollisions(testPlayer,documentModel,previous);camera.x+=(testPlayer.x-camera.x)*Math.min(1,dt*5);camera.y+=(testPlayer.y-camera.y)*Math.min(1,dt*5);render();}requestAnimationFrame(frame);}requestAnimationFrame(frame);

for(const button of document.querySelectorAll('[data-tool]'))button.addEventListener('click',()=>setTool(button.dataset.tool));for(const button of document.querySelectorAll('[data-palette]'))button.addEventListener('click',()=>{activePalette=button.dataset.palette;if(activePalette==='terrain'){selectedAssetId='terrain-0';activeLayer='ground';setTool('brush');}else{selectedAssetId=activePalette==='architecture'?'architecture-0':'prop-0';activeLayer=activePalette==='architecture'?'structures':'props';setTool('object');}refreshAssets();});
document.querySelector('#asset-search').addEventListener('input',refreshAssets);document.querySelector('#grid-toggle').addEventListener('click',(event)=>{gridVisible=!gridVisible;event.currentTarget.classList.toggle('active',gridVisible);render();});document.querySelector('#snap-toggle').addEventListener('click',(event)=>{snapEnabled=!snapEnabled;event.currentTarget.classList.toggle('active',snapEnabled);});
document.querySelector('#undo').addEventListener('click',undo);document.querySelector('#redo').addEventListener('click',redo);document.querySelector('#delete-entity').addEventListener('click',deleteSelected);document.querySelector('#duplicate-entity').addEventListener('click',duplicateSelected);document.querySelector('#export-map').addEventListener('click',exportMap);document.querySelector('#import-map').addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',()=>{if(fileInput.files[0])importMap(fileInput.files[0]);fileInput.value='';});document.querySelector('#reset-map').addEventListener('click',resetStarter);document.querySelector('#new-map').addEventListener('click',newBlankMap);document.querySelector('#playtest').addEventListener('click',togglePlaytest);document.querySelector('#map-name').addEventListener('change',(event)=>{snapshot();documentModel.name=event.target.value.trim()||'Untitled Village';afterMutation();});
canvas.addEventListener('pointerdown',onPointerDown);canvas.addEventListener('pointermove',onPointerMove);canvas.addEventListener('pointerup',onPointerUp);canvas.addEventListener('pointercancel',onPointerUp);canvas.addEventListener('contextmenu',(event)=>event.preventDefault());canvas.addEventListener('wheel',(event)=>{event.preventDefault();const before=screenToWorld(event.clientX,event.clientY),factor=Math.exp(-event.deltaY*.0012);camera.zoom=Math.max(.08,Math.min(2.2,camera.zoom*factor));const after=screenToWorld(event.clientX,event.clientY);camera.x+=before.x-after.x;camera.y+=before.y-after.y;clampCamera();render();},{passive:false});
window.addEventListener('keydown',(event)=>{const tag=event.target.tagName;if(tag==='INPUT'||tag==='SELECT')return;keys.add(event.key.toLowerCase());if(event.code==='Space'){spaceHeld=true;event.preventDefault();}if(event.key==='Escape'&&playtesting){togglePlaytest();return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='y'){event.preventDefault();redo();}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();documentModel=saveMapDocument(documentModel);document.querySelector('#save-state').textContent='SAVED LOCALLY';}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='d'){event.preventDefault();duplicateSelected();}else if(event.key==='Delete')deleteSelected();else if(!playtesting&&['v','b','o','x','c','t','p','h'].includes(event.key.toLowerCase()))setTool({v:'select',b:'brush',o:'object',x:'erase',c:'collision',t:'trigger',p:'spawn',h:'pan'}[event.key.toLowerCase()]);else if(!playtesting&&(event.key.toLowerCase()==='q'||event.key.toLowerCase()==='e')){const entity=currentEntity();if(entity&&documentModel.objects.includes(entity)){snapshot();entity.rotation+=(event.key.toLowerCase()==='q'?-15:15)*Math.PI/180;afterMutation();}}});window.addEventListener('keyup',(event)=>{keys.delete(event.key.toLowerCase());if(event.code==='Space')spaceHeld=false;});window.addEventListener('resize',resize);
bindInspector();refreshAssets();refreshLayers();refreshInspector();refreshMapStats();updateHistoryButtons();resize();
